<?php

namespace AppBundle\Repository;

/**
 * BienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienRepository extends \Doctrine\ORM\EntityRepository
{
    public function findListeDesc()
    {
        return $this->createQueryBuilder('b')->orderBy('b.id','DESC')->getQuery()->getResult();
    }
}
