<?php

namespace AppBundle\Repository;

/**
 * CarousselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarousselRepository extends \Doctrine\ORM\EntityRepository
{
    public function findListDesc()
    {
        return $this->createQueryBuilder('c')->orderBy('c.id','DESC')->getQuery()->getResult();
    }

    public function findList($domaine)
    {
        return $this->createQueryBuilder('c')
                    ->where('c.domaine = :id')
                    ->andWhere('c.statut = 1')
                    ->setParameter('id', $domaine)
                    ->getQuery()->getResult()
            ;
    }
}
