<?php

namespace AppBundle\Repository;

/**
 * DomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * liste ordonné
     */
    public function liste()
    {
        return $this->createQueryBuilder('d')->orderBy('d.libelle', 'ASC');
    }
}
