<?php

namespace AppBundle\Repository;

/**
 * ProduitImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitImageRepository extends \Doctrine\ORM\EntityRepository
{
}
