<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProduit($produit)
    {
        return $this->createQueryBuilder('p')->where('p.id = :produit')->setParameter('produit', $produit);
    }

    public function getProduit($liste = null)
    {
        if (!$liste){
            return $this->createQueryBuilder('p')
                        ->select('count(p.id)')
                        ->getQuery()->getSingleScalarResult()
                ;
        }else{
            return $this->createQueryBuilder('p')
                        ->getQuery()->getResult()
                ;
        }
    }
}
