<?php

namespace AppBundle\Repository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findListDesc()
    {
        return $this->createQueryBuilder('s')->orderBy('s.id', 'DESC')->getQuery()->getResult();
    }

    /**
     *
     */
    public function findList()
    {
        return $this->createQueryBuilder('s')
                    ->where(':periode BETWEEN s.dateDebut AND s.dateFin')
                    ->andWhere('s.statut = 1')
                    ->setParameter('periode', date('m/d/Y',time()))
                    ->getQuery()->getResult()
            ;
    }
}
