<?php

namespace AppBundle\Repository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findListDesc()
    {
        return $this->createQueryBuilder('s')->orderBy('s.id', 'DESC')->getQuery()->getResult();
    }
}
